version: '3'

services:
  app:
    build: .
    image: mahmoudsoliman/notification-service
    ports:
      - 8000:8000
    depends_on:
      - mysql
      - rabbitmq
    links: 
      - mysql:mysql
      - rabbitmq:rabbitmq
    command: npm start
  
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: notifications
    expose:
      - 33060
      
  
  rabbitmq:
    image: rabbitmq:3.7-management
    expose:
      - 5672